### ISSUE TITLE
Using it?

### ISSUE THREAD

**Issue by DecoyDesignz** [runescapejon/PokeTextures#1]
Hey i've tried running the build.bat file but it doesn't really make an artifact or a .jar for the mod/plugin. I was just wondering how this works, if it works for reforged 6.3.4 and if you can help out.

**Comment by runescapejon** [comment]
I had compile it on the release tab on github here is the link
https://github.com/runescapejon/PokeTextures/releases
and yes it does work for 6.3.4

**Comment by runescapejon** [comment]
Also more information on how it works i written it here 
https://github.com/runescapejon/PokeTextures/blob/master/README.md

**Comment by DecoyDesignz** [comment]
Awesome, does it have permission nodes?

**Comment by runescapejon** [comment]
- poketexture.spawn
- poketexture.ptgive

**Comment by DecoyDesignz** [comment]
And finally is there anyway to make the natural spawns on pixelmon have those custom textures using this? or will I need a different mod/plugin?

**Comment by runescapejon** [comment]
Sorry you would need a different plugin for that

**Comment by DecoyDesignz** [comment]
Any ideas or recommendations? it used to be spawn of psyduck or something, but that doesnt work anymore. Thanks for the help and the plugin is perfect.

**Comment by runescapejon** [comment]
Sorry i don't know of any plugins that does what your asking for it to be naturally spawn with custom textures.

**Comment by DecoyDesignz** [comment]
No problem :+1: I'm just happy that my custom textures work, Good job on the plugin.
