### ISSUE TITLE
I dont quite understand :/

### ISSUE THREAD

**Issue by Xerney** [runescapejon/PokeTextures#10]

**Comment by Xerney** [comment]
erm so i tryed to run this on a private server cause its a server side mod but for some reason the commands are not working? do i need another mod to make it work?

**Comment by Xerney** [comment]
![pokemon thing](https://user-images.githubusercontent.com/51864359/59631190-24ed2800-913f-11e9-9589-f2fcb4e2c027.PNG)

**Comment by Xerney** [comment]
this is my texture pack folder

**Comment by runescapejon** [comment]
Yes you would need
- Pixelmon 
- SpongeForge

**Comment by Xerney** [comment]
ok thanks and also is my texture pack laid out properly?

**Comment by Xerney** [comment]
i figured it out thanks :)
