### ISSUE TITLE
No Way To Summon Shiny Pokemon

### ISSUE THREAD

**Issue by DrTinyFace** [runescapejon/PokeTextures#11]
I was playing around with the plugin today and realized there's no way to summon a shiny variant of a Pokemon right now. I had planned to add special shiny versions of specific Pokemon and I was wondering if this is something that could be added to the plugin.

**Comment by runescapejon** [comment]
What? can you explain a bit more? also can't you just have a custom texture creating custom shinys?

**Comment by DrTinyFace** [comment]
Sure, not a problem.

So basically what I wanted to do is create a custom shiny variant of a Pokemon. I'll give an actual example from my server. Right now, I have an alternate skin for Weedles called "Albino", which is just a pale white version of a Weedle. What I wanted to do was make a super rare variant of Albino called "Melanistic" that still uses the Albino spawn rates, but multiplies them by the shiny spawn rate to make it significantly rarer. 

So for example, if my Albino Weedle had a spawn rate of 1/100, and I had the shiny spawn rate set to 1/1000 on my server, that would cause the Melanistic Weedle to have a spawn rate of 1/10,000 (since the Weedle would have to be both shiny and Albino to actually become a Melanistic Pokemon).

One way of working around this would be if we could make multiple folders worth of Pokemon spawn naturally and with different spawn rates, but unless I'm understanding the config file incorrectly, this is not possible right now. But the idea would be that I could set up one folder named "Melanistic" and another named "Albino" and have them both spawn naturally. So something like this:

`CustomTexture=Albino,Melanistic`

With this way, you'd also have to have a spawn rate for each folder though, so basically something like this:

`Chance=2,1`

Or maybe more like this:

`Chance=Albino:2,Melanistic:1`

Also, partially unrelated, but being able to set the spawn rate for custom skins to be significantly lower than 1/100 would be really nice too. Since some people (like me) might prefer to have their custom skins be rarer than shinies (which can already be changed to be numbers as small as 1/100,000 or smaller), a maximum rarity such as 1/10,000 would be much nicer than the current 1/100.

If you'd like, I can try and take a look at the code in a bit and see if I can submit a pull request with what I mean :)

**Comment by runescapejon** [comment]
This was an upcoming update i just haven't had time due to college and finals are coming up but feel free to make a PR thank you.

**Comment by DrTinyFace** [comment]
No worries, there's no rush for it! I didn't realize it was already an upcoming update, but if I get the chance I'll still put in a PR for you.

Great plugin by the way! :)
