### ISSUE TITLE
Just questions

### ISSUE THREAD

**Issue by Xerney** [runescapejon/PokeTextures#12]
When do you think the next update will happen?
When we have multiple folders for textures will you remove or change the config that only allows 1 folder so we can use multiple folders at once?

**Comment by runescapejon** [comment]
sorry for the late reply but what do you mean?

**Comment by Xerney** [comment]
Also sorry for late reply myself, like we can have multiple custom texture folders for example custom-halloween and also custom-chirstmas etc and stuff

**Comment by runescapejon** [comment]
Yes for `/ptgive` and `/ptspawn` those commands you can use mutiple custom texture folders. Just currently not for natural spawn pokemon. That is coming as a feature soon.

**Comment by Xerney** [comment]
ok thanks you can close now
