### ISSUE TITLE
How to be able to give pixelmon with colored names?

### ISSUE THREAD

**Issue by projectkanto** [runescapejon/PokeTextures#13]
Hi! I love this plugin and it works amazing! I have a few questions as ive seen on several servers that use your plugin. So, is there a way to make the custom textured pokemon have colored names per each texture folder? Such as if they are in crates with different themes, how can I make it so that when a player wins the custom texture say in a crate, it will also be given with the color name per folder theme? Like if a player is given a midnight mewtwo in custom-midnight it will be given to player with the purple color name, or if a player is given a custom-rainbow lugia, it will given to player with rainbow colored name. I see theres a option in config but is this only for one folder and spawning instead of giving and different folders? Or is this a plugin on its own?  If this is possible can you give me a example of config on how to add the colors per folder or multiple folders? They wouldn't be spawned in, but given through the /ptgive command from crates. I see some servers have this feature, but all their custom pokemon get sent to players from crates with colored names on them already per theme. I get really confused by configs so if this is possible would you mind replying with a like 3 or 4 lines of examples for different folders with name color examples?

**Comment by runescapejon** [comment]
`is there a way to make the custom textured pokemon have colored names per each texture folder` 
no there not a way. and sorry i do not understand the rest of the questions.

EDIT: but this plugin require a rewrite to give more features that has been request but i haven't had the time do so.
