### ISSUE TITLE
how to get custom pokemon in the pixelmon spawner?

### ISSUE THREAD

**Issue by GladionSM** [runescapejon/PokeTextures#16]
how do i go about added custom textures to the spawner blocks ? im working on a safari for my server but id like the molten textures to spawn in the desert etc

**Comment by runescapejon** [comment]
To make custom texture work for only spawner block yeah not currently a feature.

**Comment by GladionSM** [comment]
ok maybe if u are still working on this u can add it apart of the spawning but thanks for letting me know

**Comment by runescapejon** [comment]
Most likely this plugin will be rewritten to apply more and more features but wont happen anytime soon because I'm busy with exams.

**Comment by GladionSM** [comment]
ok if i can figure out how am i allowed to edit it ? to try to make them spawn in the spawners or?

**Comment by runescapejon** [comment]
Sure feel free this plugin is free to use and to modify however you see fit.

**Comment by GladionSM** [comment]
ok

**Comment by GladionSM** [comment]
quick question what part did u make it have 1 folder access? so i can make it to be two?

**Comment by runescapejon** [comment]
you can spawn them and give them with multiple folders it's just not for natural spawn with texture feature https://github.com/runescapejon/PokeTextures/blob/master/src/main/java/com/runescapejon/poketexture/main/ListenerSpawn.java#L22
