### ISSUE TITLE
GWM Crates

### ISSUE THREAD

**Issue by RafasDasGracas** [runescapejon/PokeTextures#17]
I was using a puglin of crates, and the ptgive command doesnt work. any ideia why?

**Comment by runescapejon** [comment]
Well your not providing much information. For me to assist you in anyway i can. Can you list the following
What version of Poketextures  you have and also what version of GWM crates do you have?
And also is there any indication of any error you may see ? if your unable to detect any error you can also free feel to upload your latest.log here and I am able to see what exactly is wrong.

**Comment by RafasDasGracas** [comment]
Using GWMCrates 4.6 and PokeTextures-1.12.2.-S7.1.jar no error. I open the crate and when the command "ptgive [Pokemon] %PLAYER_NAME% [custom-texture]" is supposed to work nothing happens. Nothing in-game or in console

**Comment by runescapejon** [comment]
Interesting, have you try typing that command manually without using the crate?

**Comment by RafasDasGracas** [comment]
Yes if I type it in-game it works perfectly. But using the crate doesnt work

**Comment by runescapejon** [comment]
I believe it's a crate issue. Have you check to see if there any crate error ?

**Comment by RafasDasGracas** [comment]
I did and nothing

**Comment by runescapejon** [comment]
Is it just this command, have you tried others for general testing?

**Comment by RafasDasGracas** [comment]
Yes and they work, only this command

**Comment by runescapejon** [comment]
Sorry i am not really familiar with GWMcrate,
Is it possible for you to join this discord channel https://discord.gg/NhMHTc
because this is just an crate issue, the developer of the plugin would be more then happy to guide you <3

**Comment by RafasDasGracas** [comment]
Already there talking to you i guess xD im Solex

**Comment by runescapejon** [comment]
fixed
