### ISSUE TITLE
Wild Pokemon Spawns

### ISSUE THREAD

**Issue by Catassassin** [runescapejon/PokeTextures#4]
I was curious to if there's any way to enable wild spawns of pokemon with special textures. I saw on an old thread you said you weren't doing it yet, wondering if that changed. Also I don't know if you have a patreon or paypal I could donate to, but I'd love to support you since I use this plugin so much.

**Comment by runescapejon** [comment]
No need to pay for something like this i will do it once i am free. If anything donate to the Pixelmon mod to help them keep the mod alive.

**Comment by runescapejon** [comment]
Could you or @mcmiked explain how would you want them to spawn. This can help me determine how to properly make the feature for you both. Explain how either having them by chances or always something in full detail.

**Comment by mcmiked** [comment]
Michael Danyluk

Ceo/Owner Mad Mike Movies/Affordable Window Washing/ YPR Chase Team

Coach and Entrepreneur

www.createyourownfreedom.net<http://www.energyforlife.mychoices.biz>

**Comment by mcmiked** [comment]
Okay so I don't know if either are possible or what works best for you, but I thought of 2 options for the spawns that would work great. Possibly mergeable.

So for one, it effects the pokemons spawns globably. For example something that lets us pick a pokemon like:
 Pokemon: Dratini   Custom Skin: Metal    Spawn Variant Chance: 5%       making all dratinis that spawn server wide have a 5% chance to be Metal skin. and have those options. Maybe a window like when you are editing a trainer, expect the list can be larger and each line is a different custom skin. (attached of pic of the trainer window) Something like that we can scroll and just keep adding custom variants as needed/wanted and pick their individual spawn chances.

Then the other option would be to do it by Biomes
Pokemon: Dratini   Custom Skin: Metal  Spawn Biomes: Swampland, Swampland M   Spawn variant chance: 5% Then dratini has a 5% chance to spawn in that particular biome. They could be on the same thing and if a biome isnt selected, then it effects spawns globally, if a biome is selected, it only effects spawns there.

________________________________

**Comment by mcmiked** [comment]
Or even if those kind of variables had to be in a text form outside of server, and we had to update it, then the plug in checks it for us, and applies the info that works. I'm not sure what is all possible etc for you to do.

________________________________

**Comment by mcmiked** [comment]
Also I am not sure you are aware how amazing an update like this on your plug in will be, and how overly accepted by the community it will be. If i were you, I would charge for this update if you do this to be honest. Even 2-5$ per plug in license, you will earn ALOT. Once word gets out about a plugin that allows customs spawning, people will come in crowds to get your plugin. Ill be someone telling ALOT of server owners about this plugin update. So just thought I would let you know if you put a price tag on it like that, it wouldnt change people getting it, They will get it just as fast even if its a few bucks.

You allowing custom skins to naturally spawn is a game changer for the community, just wanted to let you know in case you didn't. People will definitely donate if you don't charge, but they will pay and probably donate as well. I will be donating if you don't charge, but you really should for this update, even if its only 2$ USD. You will sell hundreds of them if not thousands over the next 6-12 months.


________________________________

**Comment by mcmiked** [comment]
Here is a text file config from an different older mod that use to let use make custom spawns in custom biomes of regular pokemon. something structured like this that can pull custom textures instead would work amazing.

________________________________

**Comment by runescapejon** [comment]
I wont be charging anyone. All i ask is for your patient on the new feature. So, i can be able to write up something the right way so it wont have any performance degrading due to spawning.

**Comment by mcmiked** [comment]
Okay well I will definitely encourage people to donate and no rush what do ever, do it how ever works best for you :)

-------- Original message --------

**Comment by runescapejon** [comment]
The `Spawn Biomes: ` option I'm not going to do because that can be configure by pixelmon json files it's self. Also ` Pokemon: Dratini ` only 1 pokemon ?

**Comment by runescapejon** [comment]
https://github.com/runescapejon/PokeTextures/releases/tag/1.3

**Comment by mcmiked** [comment]
When I have the new mod installed, how do I edit the config to spawn the textures?

________________________________

**Comment by mcmiked** [comment]
The .jar file doesnt let you, but the source code file does. Do I download them seperate and put one in a place, and the other else where. Found in the source code where to edit.

________________________________

**Comment by mcmiked** [comment]
Okay I found the config file after it loads, how ever, one last issue. You can only chose one custom folder. Attached is a pic of the different types of custom skins we have.
Is there a way to set up the config so we can use multiple custom folders and set which pokemon in that folder spawn. Example I could chose custom shadow, then set 3 pokemon in it, then do another custom folder area, and pick 5 from that, etc

________________________________

**Comment by runescapejon** [comment]
currently trying add that as a feature.

**Comment by mcmiked** [comment]
If you could make it so the 1-100 chance is customizable by individual  pokemon would be awesome as well. So I could have a 5% chance on a metal dratini, but maybe only 1% chance on a shadow nidorino, have it so you can make multiple variations of your current set up would be amazing

________________________________

**Comment by runescapejon** [comment]
There a lot of pokemon for a request like this it's on a larger scale i would have to carefully thought out how to properly write this but i will see what i can do.
