### ISSUE TITLE
Format of Folder for Textures (question)

### ISSUE THREAD

**Issue by Dragonoffire** [runescapejon/PokeTextures#5]
When you install the plugin and are setting it up for natural spawning, where do you put the folder containing the textures, and does it work like how pixelmon does where you have a bunch of folders with custom-(type) and within it, there's a bunch of pokemon textures.

**Comment by Dragonoffire** [comment]
I've tried just leaving an image in the folder with an image of the pokemon, and putting an image inside of a folder for custom-paladin, inside that is the aron.png skin

**Comment by runescapejon** [comment]
It's under the configuration option called 
```
# Custom Texture this option give the ability to choose what custom texture folder it will use
CustomTexture=
```
this is where you place your custom-types for example my folder is called `custom-ghost` so i type in `CustomTexture=ghost` 
if you have any more question please feel free to ask

**Comment by Dragonoffire** [comment]
Inside of that folder can you have nested folders or do all the textures need to be loose? And in what directory does it search for the folder?

**Comment by Dragonoffire** [comment]
and if you have multiple custom folders, do you list them all or give a parent folder?

**Comment by runescapejon** [comment]
Ohhh sorry i didn't include a way to have multiple custom folders only one. At the time of writing the feature i figure people would place one folder for all their naturally spawn texture pokemon. I will tag this as enhancement types to include it.

**Comment by Dragonoffire** [comment]
Ah okay, that was how I was trying to do it. It makes sense it wasn't working now. If all the textures are held in a single custom folder if there a way to have more than 1 alternate skin per pokemon? And if so how does that work in the case of spawning something in?

**Comment by runescapejon** [comment]
Yes you can have another alternate skin by placing into another folder `custom-(types)`

**Comment by Dragonoffire** [comment]
Okay, I'm still having a hard time wrapping my head around that. Sorry. Let me explain the situation, maybe that'll help. So I have around 30 types of custom folders, for example, custom-abyss, custom-dark, custom-royal. All of these are held in a folder called pokemon-textures, and some of those custom folders have overlapping pokemon, I.E. there are 3 skins for Gible. How would I go about connecting this in the config?

**Comment by runescapejon** [comment]
Can you explain on the overlapping pokemon part? not really understanding sorry

**Comment by Dragonoffire** [comment]
Sorry, that wasn’t that clear. I essentially have multiple skins for the same Pokémon, but they’re not all held in the same folder. custom-abyss, custom-royal and custom-dark all have textures for gible, so 3 total. I was asking how I could make this work.

**Comment by runescapejon** [comment]
Ohh there currently no way of doing for only naturally spawning but however there a way to give them to player the other types of texture of the same pokemon with the command `/ptgive`

**Comment by runescapejon** [comment]
But i'll try to include this as a new feature for the next update.

**Comment by Dragonoffire** [comment]
Thanks so much, I’m happy i got to the bottom of that. Looking forward to the future of the mod!

**Comment by Dragonoffire** [comment]
This is another bizarre question and is probably more pixelmon than this plugin, but if you breed a Pokémon with a special texture is the special texture passed down?

**Comment by runescapejon** [comment]
I actually don't know and yea it's a i would suggest ask pixelmon on their support.

**Comment by runescapejon** [comment]
Going to close this because i had made another issue that has list of features to add to improve the plugin.
