### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Ktendium** [runescapejon/PokeTextures#7]
Hello, Im very interested with this plugin/mod although, I dont know how or where to put this to the change the textures, Ive put it in a mods folder and the command which is on the read me doc would not work. Do you have to have Bukkit for this to work?
Im sorry if this is statted somewhere else and I was to dumb to find it...

**Comment by runescapejon** [comment]
Sorry this is only for 1.12.2 pixelmon and it's for Sponge not bukkit

**Comment by Ktendium** [comment]
Oh thank you for clarifying that although I also wish to know how to add it, so I can add new textures without overriding old ones thank you.

**Comment by runescapejon** [comment]
Which Pixelmon are you running with this plugin?

**Comment by Ktendium** [comment]
7.0.5

**Comment by Ktendium** [comment]
Im using this but I dont understand how sponge works and where to put the file.. Sorry for the misswording

**Comment by runescapejon** [comment]
Well what don't you understand what part ?

**Comment by Ktendium** [comment]
Oh I didnt understand the Sponge but it works now Thank you!

**Comment by runescapejon** [comment]
You can join the Sponge discord and ask how does it work Sponge team and me among others will gladly to help you understand here is Official Sponge discord https://discord.gg/sponge

**Comment by Ktendium** [comment]
One more question how do you make them spawn naturally?
with coloured names?

**Comment by runescapejon** [comment]
i suck at explaining things so i'll do my best on here https://pixelmonmod.com/wiki/index.php?title=Custom_textures
you see this `custom-shadow` so that the folder where you put your texture in right? so if you want whatever in that folder to spawn naturally then it's easy  just grab this config option and make it like this 
```
# Custom Texture this option give the ability to choose what custom texture folder it will use
CustomTexture=shadow
```

**Comment by Ktendium** [comment]
Ok I get the folders but do I have to add in a document or anything or do they just spawn naturally ive done /pts Onix Crystal and it worked but will 1-100 Onix's be this colour or do I have to add something to make it spawn naturally

**Comment by Ktendium** [comment]
BTw can we change the sprites via rescource pack and adding custom-sprites?

**Comment by runescapejon** [comment]
What do you mean color?
and as for sprites I'm not sure

**Comment by Ktendium** [comment]
By colour I meant skins.

**Comment by runescapejon** [comment]
the 1-100 those are chances so if you have naturally spawn custom texture pokemon and you want them to spawn more and more frequently then you set it to `100` chance if you want them to spawn rare then set it to 1 make sense?

**Comment by Ktendium** [comment]
In the ListenerSpawn.class?

**Comment by Ktendium** [comment]
?

**Comment by runescapejon** [comment]
yes

**Comment by Ktendium** [comment]
![image](https://user-images.githubusercontent.com/49605142/56103435-2f8c1500-5f76-11e9-9ac4-4b2cda987636.png)
Where do I put it?

**Comment by runescapejon** [comment]
Oh no  no no it's all in the configuration
Config/Poketexture>config

**Comment by Ktendium** [comment]
![image](https://user-images.githubusercontent.com/49605142/56103623-28193b80-5f77-11e9-9f8b-057b1edd8ad0.png)
so this?

**Comment by runescapejon** [comment]
No not inside of the plugin, there a config in your server directory a folder should be named "config" it's store in your  Forge 1.12.2 server

**Comment by Ktendium** [comment]
Its actually a single player world

**Comment by runescapejon** [comment]
You need to have Sponge installed i suggest learn how to use sponge and how to install it also please go on the discord and ask for support

**Comment by Ktendium** [comment]
could i find that in the .minecraft folder?

**Comment by Ktendium** [comment]
I have sponge installed in mods

**Comment by runescapejon** [comment]
https://www.youtube.com/watch?v=v4sqs6Hm5u0 please watch this after you learn about sponge then you can installed plugins like this one

**Comment by Ktendium** [comment]
Is this the config file?
![image](https://user-images.githubusercontent.com/49605142/56103943-b3df9780-5f78-11e9-9409-0077f69ca674.png)

**Comment by runescapejon** [comment]
Yes but open it with notepad or notepad ++ to show it's proper format

**Comment by Ktendium** [comment]
it's in notepad in that image

**Comment by Ktendium** [comment]
Do i change the false to true?
