### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by AmericanTech** [runescapejon/PokeTextures#8]
Is there a way to make it so the custom pokes to only spawn within a small set area?

**Comment by runescapejon** [comment]
like a small region of an area and nothing else? if so then no

**Comment by AmericanTech** [comment]
What about only a specific biome, like having eevee spawn in mushroom islands as well as birch forest like normal but the custom ones can only be found in mushroom islands?

**Comment by runescapejon** [comment]
Sorry currently there only a way to control the rarity of textured pokemon

**Comment by AmericanTech** [comment]
Alright, thank you for your time, and keep up the good work!
